### ISSUE TITLE
autoconf in root folder has errors

### ISSUE THREAD

**Issue by payload** [stephenrkell/liballocs#6]
I've read issue #5 and think it describes something else. This is what I get with autoconf 2.69.

```
/liballocs$ autoconf
configure.ac:15: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:16: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:65: error: possibly undefined macro: AM_CONDITIONAL
```

**Comment by stephenrkell** [comment]
Thanks for reporting this, and for being interested in liballocs.

I'm outrageously preoccupied with other work right now, so I'm unlikely to get around to these issues for a couple of weeks. As I mentioned in issue #5, the autoconfisation is a new contribution and I haven't been using it myself... your best bet for a quick fix is to avoid autoconf for now and use the contrib/checkout.sh script in the dwarfidl repo. You'll have to revert to a *pre*-autoconf version of each of the repositories it checks out, until I (or someone) fixes the autoconf.

**Comment by stephenrkell** [comment]
I've now added an autogen.sh that takes care of the autoconf/automake bootstrapping process... feel free to give it a try and let me know how you get on.

**Comment by stephenrkell** [comment]
I believe this now works, so I'm closing this ticket... feedback welcome.
