### ISSUE TITLE
Incorrect calculation of bit index in bitmap_delete?

### ISSUE THREAD

**Issue by muffpy** [stephenrkell/liballocs#62]
In [generic_malloc.c](https://github.com/stephenrkell/liballocs/blob/master/src/allocators/generic_malloc.c#L510):

`bitmap_clear_l(bitmap, ((uintptr_t) userptr - (uintptr_t) info->bitmap_base_addr) / (MALLOC_ALIGN * BITMAP_WORD_NBITS))`

...wouldn't dividing by `BITMAP_WORD_NBITS` not give us the intended bit index but instead the bitmap index within `bitmap_word_t *bitmap`? In fact, we divide by `BITMAP_WORD_NBITS` again in [librunt/bitmap.h](https://github.com/stephenrkell/librunt/blob/master/include/bitmap.h#L136) presumably to get the bitmap index there.

Proposing instead:
`bitmap_clear_l(bitmap, ((uintptr_t) userptr - (uintptr_t) info->bitmap_base_addr) / MALLOC_ALIGN)`

**Comment by stephenrkell** [comment]
Thanks for this. I think you are right! I can fix a bit later, or feel free to pull-request.

**Comment by stephenrkell** [comment]
I believe this is now fixed.
