### ISSUE TITLE
compilation failing

### ISSUE THREAD

**Issue by nivpgir** [stephenrkell/liballocs#9]
I'm trying to build liballocs, using:
 - arch linux with all dependencies on their latest version (converted dependencies from ubuntu as accurately as I could) 
 - gcc 8.2
 - arch linux standard binutils-gdb since your patched version would not compile either but it's still on version 2.30 so it should work(?)

the build fails with `make -C contrib` with the error:
```
src/dies.cpp: In member function ‘virtual dwarf::spec::opt<dwarf::core::type_scc_t> dwarf::core::type_die::get_scc() const’:
src/dies.cpp:2560:62: error: no matching function for call to ‘dwarf::spec::opt<std::shared_ptr<dwarf::core::type_scc_t> >::opt(std::shared_ptr<dwarf::core::type_scc_t>)’
      = opt<shared_ptr<type_scc_t> >(shared_ptr<type_scc_t>());
``` 

more logs can be supplied if necessary.
any idea?

**Comment by stephenrkell** [comment]
Thanks for reporting this.

Short answer: please try pulling the contrib/libdwarfpp submodule from the master branch latest. I think I just need to update the submodule to point to that.

For the binutils issue, you'll be fine for now but ultimately I need to forward-port my patches to 2.30... they're not in the mainline version, no. This only matters in some corner cases, and then only when you start telling liballocs about your custom allocators. Feel free to report your problem on my binutils-gdb fork.

**Comment by nivpgir** [comment]
checked out master on libdwarfpp but the error stays.
I also tried to clone libdwarfpp by itself and build it alone and ran into some other build errors, would you prefer I open an issue for this on the libdwarf repo? since this seems to be related to libdwarf rather than to liballocs itself?

**Comment by stephenrkell** [comment]
Yes, please report this on libdwarfpp. Before you do, pull and try again because I've just pushed a few local changesets I had sitting around.

Or do you mean there is a problem with libdwarf (not libdwarfpp)? That is built during the libdwarfpp contrib build but is a separate project (https://www.prevanders.net/dwarf.html).

**Comment by nivpgir** [comment]
I'm commenting here to try and get your attention.

I opened an issue on libdwarfpp, found the source of the problem, and after that, found out that there is a pending PR that fixes this exact issue.
It would be nice if you could take a look at that PR and apply the fixes from it so I won't have to use a patched version.
